[tool.poetry]
name = "vaga-aec"
version = "0.1.0"
description = ""
authors = ["berrytern <berrytern@gmail.com>"]
license = "Apache 2.0"
readme = "README.md"

[project]
name = "vaga-aec"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = { text = "Apache 2.0" }
requires-python = ">=3.10"
dependencies = [
    "alembic >= 1.14.0",
    "fastapi >= 0.115.5",
    "sqlalchemy[asyncio] >= 2.0.36",
    "uvicorn[standard] >= 0.32.1",
    "gunicorn >= 23.0.0",
    "pyjwt >= 2.10.1",
    "bcrypt >= 4.2.1",
    "pydantic[email] >= 2.10.2",
    "asyncpg >= 0.30.0",
    "prometheus-client >= 0.21.1",
    "redis[asyncio] >= 5.2.1",
    "aiosmtplib >= 3.0.2",
    "jinja2 >= 3.1.5",
    "dependency-injector>=4.48.2",
]

[dependency-groups]
dev = [
    "pytest >= 8.3.3",
    "pre-commit >= 4.0.1",
    "black >= 24.10.0",
    "flake8 >= 7.1.1",
    "pytest-cov >= 6.0.0",
    "pytest-asyncio >= 0.24.0",
    "mypy >= 1.14.0"
]

[tool.pytest.ini_options]
pythonpath = [
    "."
]
