{
 "title": "Service Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(http_requests_total{group=~\"prod|dev\", status!=\"200\"}[1m])",
     "legendFormat": "{{group}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(http_requests_total{group=\"dev\"}[1m])",
     "legendFormat": "{{group}} {{path}} {{status}}"
    }
   ]
  },
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Daily Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg_over_time((sum without()(up) or (0 * sum_over_time(up[5m])))[1d:1m])",
     "legendFormat": "{{group}} {{job}}"
    }
   ]
  },
  {
   "title": "Monthly Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg_over_time((sum without()(up) or (0 * sum_over_time(up[5m])))[30d:1m])",
     "legendFormat": "{{group}} {{job}}"
    }
   ]
  }
 ]
}